import gql from "graphql-tag";

export const GET_ALL_USERS = gql`
        query{
  auth{
    getUserDetails{
      data{
        id
        email
        userType
        isVerified
        status
        createdAt
        profile{
          firstName
          lastName
          contactNumber
          DateOfBirth
          Address{
            City
            District
            State
          }
        }
        additionalInformation{
          isStaff
          hasOrganization
        }
      }
      error{
        message
        code
      }
    }
  }
}
`;

export const GET_USER = gql`
            query{
  auth{
    getUserDetails{
      data{
        id
        email
        userType
        isVerified
        status
        createdAt
        profile{
          firstName
          lastName
          contactNumber
          DateOfBirth
          Address{
            City
            District
            State
          }
        }
        additionalInformation{
          isStaff
          hasOrganization
        }
      }
      error{
        message
        code
      }
    }
  }
}
`;